---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: data-pool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3  # Store 3 copies across different hosts
    requireSafeReplicaSize: true
  compressionMode: aggressive
  parameters:
    compression_algorithm: lz4
    compression_required_ratio: 0.875  # Only compress if >87.5% reduction
    pg_num: 32  # Fewer PGs for small pool
    pgp_num: 32
  deviceClass: ""  # Leave empty to use all device classes
  enableRBDStats: true
