---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicated-data-pool
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 3
    requireSafeReplicaSize: true
  compressionMode: none
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ec-data-pool
  namespace: rook-ceph
spec:
  failureDomain: osd
  erasureCoded:
    dataChunks: 4
    codingChunks: 2
    algorithm: jerasure
  compressionMode: none

