---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: data-pool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3  
    requireSafeReplicaSize: true
  compressionMode: none
  parameters:
    pg_num: "32"
    pgp_num: "32"
  deviceClass: ""
  enableRBDStats: true
