---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  releaseName: rook-ceph
  interval: 10m
  chart:
    spec:
      chart: rook-ceph
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 10m
  values:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector: {}
    tolerations: []
    currentNamespaceOnly: false
    # Enable discovery daemon
    enableDiscoveryDaemon: true
    csi:
      enableRbdDriver: true
      enableCephfsDriver: false
      enableGrpcMetrics: false
      pluginTolerations: []
      pluginNodeAffinity: {}
      provisionerTolerations: []
      provisionerNodeAffinity: {}
