apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: "0.30.0"  # Set specific version or omit to use latest
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: awx 
      interval: 1h
  install:
    createNamespace: false
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/hostname: awx.mehar.me
      hosts:
        - host: awx.mehar.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - awx.mehar.me
          secretName: awx-tls
