---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: awx
      interval: 1h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    AWX:
      enabled: false  
